# Clase 1 - Semana 2
#### Tópicos Selectos De Matemáticas Aplicadas II: Análisis de Datos con Python

### Diccionario

Un diccionario almacena una colección de pares clave-valor, donde la clave y el valor son objetos Python. Cada clave está asociada a un valor, de modo que dicho valor se pueda recuperar, insertar, modificar o borrar convenientemente dada una determinada clave.

Una forma de crear un diccionario es utilizando llaves **"{}"** y signos de dos puntos **":"** para separar claves y valores:

In [1]:
d1 = {'a': 'algún valor', 'b': [1, 2, 3, 4]}
d1

{'a': 'algún valor', 'b': [1, 2, 3, 4]}

Se puede acceder a los elementos, insertarlos o formar conjuntos con ellos utilizando la misma sintaxis que para acceder a los elementos de una lista:

In [2]:
d1[7] = 'un entero' #añadir a diccionario

In [3]:
d1

{'a': 'algún valor', 'b': [1, 2, 3, 4], 7: 'un entero'}

In [4]:
d1['a'] #buscar con llave

'algún valor'

In [5]:
'a' in d1

True

El método **keys** y **values** proporciona iteradores de las claves y los valores del diccionario, respectivamente.

In [6]:
list(d1.keys())

['a', 'b', 7]

In [7]:
list(d1.values())

['algún valor', [1, 2, 3, 4], 'un entero']

Se puede combinar un diccionario con otro con el método **update**:

In [8]:
d2={'z': 'azul', 'c': 12}

In [9]:
d1.update(d2)

In [10]:
d1

{'a': 'algún valor', 'b': [1, 2, 3, 4], 7: 'un entero', 'z': 'azul', 'c': 12}

# Funciones

Las funciones son el método principal y más importante de Python para organizar y reutilizar código. Como regla general, si nos anticipamos a la necesidad de repetir el mismo código o uno muy parecido más de una vez, puede merecer la pena escribir una función que se pueda reutilizar.

Las funciones se declaran con la palabra clave **def**. Una función
contiene un bloque de código, con un uso opcional de la palabra clave **return**:

In [12]:
def sumar(a, b):
    x = a+b
    return x

In [17]:
sumar(4324,234)

4558

Una función que resuelva ecuaciones de la forma $$ax+b=0$$

In [18]:
def sol(a,b):
    if a>0 or a<0:
        x=-b/a
        return x
    else: print('error')

In [19]:
sol(0,5)

error


Si Python alcanza el final de una función sin encontrar una sentencia return, devuelve automáticamente None.

In [20]:
def f1(x):
    print(x)

In [21]:
print(f1('azul'))

azul
None


Una función con un argumento opcional z que tiene el valor predeterminado 

In [22]:
def mi_func(x, y, z=2):     # z=1.5
    if z > 1:
        return z * (x + y)
    else:
        return z / (x + y)

In [25]:
mi_func(3,2)

10

Cualquier variable asignada dentro de una función está asignada  al espacio de nombres local.

In [30]:
h=2

In [27]:
def func():
    h = []
    for i in range(5):
        h.append(i)  

In [31]:
h

2

In [46]:
func()

In [47]:
h=[]

In [48]:
def func():
    for i in range(5):
        h.append(i)

In [49]:
h

[]

Cada llamada a 'func' modificará la lista a:

In [44]:
func()
h

[0, 1, 2, 3, 4]

In [45]:
func()
h

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

Una **expresión regular** (o regex, por regular expression) es una secuencia de caracteres que define un patrón de búsqueda en cadenas de texto. Se usa para buscar, validar, reemplazar o dividir texto de forma eficiente y flexible.

In [53]:
capitales = ['#Ciudad Victo*ria', 'cuerna#vaca', 'Morelia!', 'xalapa', 'Tepic', 'hermos*illo',
 'toluca?', 'San? Luis Potosí', ' *Mexicali', 'Villahermosa', 'Tuxtla Gutiérrez#',
 'Colima', 'la Paz#', 'Guadalajara', 'C*ampeche!', 'Durango', 'Zacatecas',
 '!Chetumal', ' Ciudad# de México', 'chilpancingo*', ' Chihua#hua', '?Aguascalientes',
 'Oaxaca de Juárez*', '?Puebla', 'Quer?étaro', 'Mérida', 'guanajuato',
 'pachu*ca', '#Saltillo#', 'Culiacán!', 'Tlaxcala', 'monterrey']

Una forma de limpiar la lista es utilizando métodos de cadena de texto internos junto con el módulo de librería estándar **re** para las expresiones regulares:

In [57]:
import re
def limpiar_cadenas(strings):
    result = []
    for value in strings:
        value = value.strip()  # suprime blancos u otro carácter especificado del final 
                               #o del principio de una expresión 
        value = re.sub('[!*#?]', '', value) #reemplaza todas las ocurrencias de un patrón 
                                           #por el texto que especifiquemos
        value = value.title() #convierte la primera letra de cada palabra de una cadena 
                              # a mayúsculas.
        result.append(value) 
    return result

In [58]:
capitales_limpias = limpiar_cadenas(capitales)

capitales_limpias.sort()

In [59]:
capitales_limpias

['Aguascalientes',
 'Campeche',
 'Chetumal',
 'Chihuahua',
 'Chilpancingo',
 'Ciudad De México',
 'Ciudad Victoria',
 'Colima',
 'Cuernavaca',
 'Culiacán',
 'Durango',
 'Guadalajara',
 'Guanajuato',
 'Hermosillo',
 'La Paz',
 'Mexicali',
 'Monterrey',
 'Morelia',
 'Mérida',
 'Oaxaca De Juárez',
 'Pachuca',
 'Puebla',
 'Querétaro',
 'Saltillo',
 'San Luis Potosí',
 'Tepic',
 'Tlaxcala',
 'Toluca',
 'Tuxtla Gutiérrez',
 'Villahermosa',
 'Xalapa',
 'Zacatecas']

Python soporta las denominadas funciones anónimas o **lambda**, una forma de escribir funciones que consisten en una única sentencia.

In [60]:
def short_function(x):
    return x ** 2

In [62]:
equiv = lambda x: x ** 2

In [66]:
short_function(345)

119025

In [65]:
equiv(345)

119025

## 📦 Paquete NumPy 

Una de las características fundamentales de **NumPy** es su objeto central: el **`ndarray`** (*n-dimensional array*), que representa una estructura de datos eficiente y versátil para almacenar y manipular arreglos de múltiples dimensiones.

El objeto `ndarray` permite:

- Representar grandes conjuntos de datos numéricos en forma de vectores, matrices o tensores.
- Realizar operaciones matemáticas de manera **vectorizada**, es decir, **sin bucles explícitos**, lo que mejora notablemente el rendimiento.
- Usar una **sintaxis concisa** y **similar a las operaciones escalares** (por ejemplo, suma, multiplicación, exponenciación), pero aplicadas a todos los elementos del arreglo.

Esto hace que NumPy sea ideal para tareas de **cálculo científico, álgebra lineal, procesamiento de señales**, y como base para otras bibliotecas como **Pandas**, **SciPy**, **Scikit-learn**, entre otras.


In [67]:
import numpy as np

La función **np.array()** convierte una lista (o lista de listas, o cualquier secuencia) en un objeto ndarray.

In [69]:
datos = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [70]:
datos

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

| Función                            | Descripción                                              | Ejemplo                            |
|------------------------------------|----------------------------------------------------------|------------------------------------|
| `np.array(obj)`                    | Convierte listas, tuplas u objetos similares en un `ndarray` | `np.array([1, 2, 3])`              |
| `np.zeros(shape)`                  | Arreglo lleno de ceros                                   | `np.zeros((2, 3))`                 |
| `np.ones(shape)`                   | Arreglo lleno de unos                                    | `np.ones(5)`                       |
| `np.full(shape, fill_value)`       | Arreglo lleno con un valor específico                    | `np.full((3, 3), 7)`               |
| `np.eye(N)`                        | Matriz identidad de tamaño `N × N`                       | `np.eye(4)`                        |
| `np.arange(start, stop, step)`     | Arreglo con valores equiespaciados                      | `np.arange(0, 10, 2)`              |
| `np.linspace(start, stop, num)`    | Arreglo con `num` valores equidistantes entre `start` y `stop` | `np.linspace(0, 1, 5)`        |
| `np.random.rand(d0, d1, ...)`      | Arreglo con valores aleatorios uniformes en [0, 1)       | `np.random.rand(2, 4)`             |
| `np.random.randn(d0, d1, ...)`     | Arreglo con valores de una distribución normal estándar  | `np.random.randn(3, 3)`            |
| `np.empty(shape)`                  | Arreglo sin inicializar (contiene basura de memoria)     | `np.empty((2, 2))`                 |
| `np.reshape(array, new_shape)`     | Cambia la forma de un `ndarray`                          | `np.reshape(np.arange(6), (2, 3))` |


In [71]:
datos

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [72]:
datos*10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [73]:
datos+datos

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [74]:
datos.shape # una tupla indica el tamaño de cada dimensión

(2, 3)

Una lista de listas de la misma longitud, serán convertidas en un array multidimensional:

In [80]:
datos2 = [[1, 2, 3, 4], [5.3, 62.3, 7, 8]]

In [81]:
arr2 = np.array(datos2)

In [82]:
arr2

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5.3, 62.3,  7. ,  8. ]])

Como datos2 era una lista de listas, el array NumPy arr2 tiene dos dimensiones

In [83]:
arr2.ndim

2

In [84]:
arr2.dtype

dtype('float64')

Otra función que nos permite crear un array NumPy es **numpy.arange**. Esta función genera un conjunto de números entre un valor de inicio y uno final, pudiendo especificar un incremento entre los valores.

In [87]:
arr = np.arange(1,20,.05)

In [88]:
arr

array([ 1.  ,  1.05,  1.1 ,  1.15,  1.2 ,  1.25,  1.3 ,  1.35,  1.4 ,
        1.45,  1.5 ,  1.55,  1.6 ,  1.65,  1.7 ,  1.75,  1.8 ,  1.85,
        1.9 ,  1.95,  2.  ,  2.05,  2.1 ,  2.15,  2.2 ,  2.25,  2.3 ,
        2.35,  2.4 ,  2.45,  2.5 ,  2.55,  2.6 ,  2.65,  2.7 ,  2.75,
        2.8 ,  2.85,  2.9 ,  2.95,  3.  ,  3.05,  3.1 ,  3.15,  3.2 ,
        3.25,  3.3 ,  3.35,  3.4 ,  3.45,  3.5 ,  3.55,  3.6 ,  3.65,
        3.7 ,  3.75,  3.8 ,  3.85,  3.9 ,  3.95,  4.  ,  4.05,  4.1 ,
        4.15,  4.2 ,  4.25,  4.3 ,  4.35,  4.4 ,  4.45,  4.5 ,  4.55,
        4.6 ,  4.65,  4.7 ,  4.75,  4.8 ,  4.85,  4.9 ,  4.95,  5.  ,
        5.05,  5.1 ,  5.15,  5.2 ,  5.25,  5.3 ,  5.35,  5.4 ,  5.45,
        5.5 ,  5.55,  5.6 ,  5.65,  5.7 ,  5.75,  5.8 ,  5.85,  5.9 ,
        5.95,  6.  ,  6.05,  6.1 ,  6.15,  6.2 ,  6.25,  6.3 ,  6.35,
        6.4 ,  6.45,  6.5 ,  6.55,  6.6 ,  6.65,  6.7 ,  6.75,  6.8 ,
        6.85,  6.9 ,  6.95,  7.  ,  7.05,  7.1 ,  7.15,  7.2 ,  7.25,
        7.3 ,  7.35,

Se puede convertir de forma explícita un array de un tipo de datos a otro utilizando el método astype de ndarray

In [89]:
arr = np.array([1, 2, 3, 4, 5])

In [90]:
arr

array([1, 2, 3, 4, 5])

In [91]:
arr.dtype

dtype('int64')

In [93]:
float_arr = arr.astype(np.float64)

In [94]:
float_arr

array([1., 2., 3., 4., 5.])

Si se convierten números en punto flotante al tipo de datos entero, la parte decimal quedará truncada:

In [95]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [97]:
arr.astype(np.int64)

array([ 3, -1, -2,  0, 12, 10])

Si tenemos un array de cadenas de texto que representan números, se puede emplear astype para convertirlos a su forma numérica:

In [98]:
numeric_strings = np.array(['1.25', '-9.6', '42.2'])

In [99]:
numeric_strings

array(['1.25', '-9.6', '42.2'], dtype='<U4')

In [101]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.2 ])

## Aritmética con arrays

Los arrays son importantes porque permiten expresar operaciones en lotes con datos sin escribir bucles for. Los usuarios de NumPy llaman a esto vectorización.

In [102]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [105]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [106]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [107]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [108]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [109]:
arr**2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [110]:
np.mean(arr)

3.5

## Funciones Comunes de NumPy Aplicadas a Arrays

| Función NumPy             | Descripción                                                       | Ejemplo de uso                  | Devuelve                          |
|---------------------------|-------------------------------------------------------------------|----------------------------------|------------------------------------|
| `np.sum(a)`               | Suma todos los elementos del array                               | `np.sum([1,2,3])`                | `6`                                |
| `np.mean(a)`              | Media aritmética                                                 | `np.mean([1,2,3])`               | `2.0`                              |
| `np.std(a)`               | Desviación estándar                                              | `np.std([1,2,3])`                | `0.816...`                         |
| `np.var(a)`               | Varianza                                                         | `np.var([1,2,3])`                | `0.666...`                         |
| `np.min(a)`               | Valor mínimo                                                     | `np.min([3,1,2])`                | `1`                                |
| `np.max(a)`               | Valor máximo                                                     | `np.max([3,1,2])`                | `3`                                |
| `np.argmin(a)`            | Índice del valor mínimo                                          | `np.argmin([3,1,2])`             | `1`                                |
| `np.argmax(a)`            | Índice del valor máximo                                          | `np.argmax([3,1,2])`             | `0`                                |
| `np.cumsum(a)`            | Suma acumulativa                                                 | `np.cumsum([1,2,3])`             | `[1, 3, 6]`                         |
| `np.diff(a)`              | Diferencias entre elementos consecutivos                         | `np.diff([1,4,9])`               | `[3, 5]`                            |
| `np.sort(a)`              | Ordena los elementos del array                                   | `np.sort([3,1,2])`               | `[1, 2, 3]`                         |
| `np.unique(a)`            | Devuelve valores únicos (sin duplicados)                         | `np.unique([1,2,2,3])`           | `[1, 2, 3]`                         |
| `np.dot(a, b)`            | Producto escalar (o producto matricial si son matrices)          | `np.dot([1,2], [3,4])`           | `11`                               |
| `np.matmul(a, b)`         | Producto matricial explícito                                     | `np.matmul(A, B)`                | matriz resultante                  |
| `np.linalg.norm(a)`       | Norma (longitud) del vector                                      | `np.linalg.norm([3,4])`          | `5.0`                              |
| `np.linalg.inv(A)`        | Matriz inversa (si existe)                                       | `np.linalg.inv(A)`               | `A⁻¹`                              |
| `np.linalg.det(A)`        | Determinante de una matriz cuadrada                             | `np.linalg.det(A)`               | escalar                            |
| `np.linalg.eig(A)`        | Autovalores y autovectores                                       | `vals, vecs = np.linalg.eig(A)`  | tupla `(valores, vectores)`       |
| `np.transpose(A)` / `A.T` | Transpuesta de una matriz                                        | `A.T`                            | matriz transpuesta                 |
| `np.reshape(a, newshape)` | Reestructura el array en otra forma compatible                  | `np.reshape([1,2,3,4], (2,2))`    | nueva matriz                       |
| `np.concatenate([a,b])`   | Une arrays en una sola dimensión                                | `np.concatenate([[1,2],[3,4]])`  | `[1, 2, 3, 4]`                     |
| `np.stack([a,b])`         | Apila arrays por una nueva dimensión                            | `np.stack([a,b], axis=0)`        | matriz 2D                          |


In [111]:
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

In [ ]:
np.linalg.norm()

In [ ]:
np.dot()

In [113]:
u/np.linalg.norm(u)

array([0.26726124, 0.53452248, 0.80178373])

In [112]:
dot_np = np.dot(u, v)
dot_manual = np.sum(u * v)

print("Producto escalar (np.dot):", dot_np)
print("Producto escalar (manual):", dot_manual)



Producto escalar (np.dot): 32
Producto escalar (manual): 32


## Tabla de Funciones Trigonométricas en NumPy

| Función NumPy             | Descripción                             | Rango de entrada      | Resultado (en radianes)        |
|---------------------------|-----------------------------------------|------------------------|--------------------------------|
| `np.sin(x)`               | Seno de `x`                             | $\mathbb{R}$  | $[-1, 1]$                 |
| `np.cos(x)`               | Coseno de `x`                           | $\mathbb{R}$  | $[-1, 1]$                 |
| `np.tan(x)`               | Tangente de `x`                         | $x \neq \frac{\pi}{2} + k\pi$ | $\mathbb{R}$           |
| `np.arcsin(x)`            | Arcoseno (inverso del seno)             | $[-1, 1]$           | $[-\frac{\pi}{2}, \frac{\pi}{2}]$ |
| `np.arccos(x)`            | Arcocoseno (inverso del coseno)         | $[-1, 1]$            | $[0, \pi]$                  |
| `np.arctan(x)`            | Arcotangente (inverso de tangente)      | $\mathbb{R}$         | $(-\frac{\pi}{2}, \frac{\pi}{2})$ |
| `np.degrees(x)`           | Convierte radianes a grados             | radianes               | grados                        |
| `np.radians(x)`           | Convierte grados a radianes             | grados                 | radianes                      |
| `np.sinh(x)`              | Seno hiperbólico                        | $\mathbb{R}$  | $\mathbb{R}$                |
| `np.cosh(x)`              | Coseno hiperbólico                      | $\mathbb{R}$  | $[1, \infty)$               |
| `np.tanh(x)`              | Tangente hiperbólica                    | $\mathbb{R}$  | $(-1, 1)$                   |
| `np.arcsinh(x)`           | Inverso de seno hiperbólico             | $\mathbb{R}$         | $\mathbb{R}$                |
| `np.arccosh(x)`           | Inverso de coseno hiperbólico           | $[1, \infty)$        | $[0, \infty)$               |
| `np.arctanh(x)`           | Inverso de tangente hiperbólica         | $(-1, 1)$            | $\mathbb{R}$                |


Sean los vectores $u=[3,4]$ y $v=[1,1]$.

- Calcula la distancia euclidiana entre $u$ y $v$.

- Normaliza ambos vectores.

In [114]:
u = np.array([3, 4])
v = np.array([1, 1])



print("Norma de u:", np.linalg.norm(u))
print("Norma de v:", np.linalg.norm(v))
print("Distancia entre u y v:", np.linalg.norm(u - v))
print("u normalizado:", u / np.linalg.norm(u))
print("v normalizado:", v / np.linalg.norm(v))

Norma de u: 5.0
Norma de v: 1.4142135623730951
Distancia entre u y v: 3.605551275463989
u normalizado: [0.6 0.8]
v normalizado: [0.70710678 0.70710678]


Sean los vectores $u=[3,4]$ y $v=[−4,3]$.

- Verifica si son ortogonales.

- Calcula la norma de cada vector. 

- Calcula el ángulo entre ellos en grados. 

In [115]:
u = np.array([3, 4])
v = np.array([-4, 3])

In [116]:
dot = np.dot(u, v)
norm_u = np.linalg.norm(u)
norm_v = np.linalg.norm(v)
cos_theta = dot / (norm_u * norm_v)

print("Producto punto:", dot)
print("Norma de u:", norm_u)
print("Norma de v:", norm_v)
print("ángulo (radianes): ", np.arccos(cos_theta))
print("ángulo (grados): ", np.degrees(np.arccos(cos_theta)))

Producto punto: 0
Norma de u: 5.0
Norma de v: 5.0
ángulo (radianes):  1.5707963267948966
ángulo (grados):  90.0
